# List of parameters for univariate methods

Univariate_Methods_Parameters = {
    'Sub_IForest':{
        'expe':{
            'no-opt':[],
            'opt':{
                'periodicity':1, 
                'n_estimators':100, 
                'max_features':1, 
                'n_jobs':1
            }
        }
    }, 
    'IForest':{ 
        'expe':{
            'no_opt':[],
            'opt':{
            'slidingWindow':100, 
            'n_estimators':100, 
            'max_features':1, 
            'n_jobs':1
            }
        } 
    },
    'Sub_LOF':{
        'expe':{
            'no-opt':[],
            'opt':{
                'periodicity':1, 
                'n_neighbors':30, 
                'metric':'minkowski', 
                'n_jobs':1
                }
        }
    }, 
    'LOF':{ 
        'expe':{
            'no-opt':[],
            'opt': {
                'slidingWindow':1, 
                'n_neighbors':30,
                'metric':'minkowski', 
                'n_jobs':1
            }
        }
    },
    'POLY':{
        'expe':{
            'no-opt': [],
            'opt':{
                'periodicity':1, 
                'power':3, 
                'n_jobs':1
            }
        }
    }, 
    'MatrixProfile':{
        'expe':{
            'no-opt':[],
             'opt':{ 
                'periodicity':1, 
                'n_jobs':1       
             }
        }     
    }, 
    'NORMA':{
        'expe':{
            'no-opt':[],
            'opt':{
                'periodicity':1, 
                'clustering':'hierarchical', 
                'n_jobs':1
            }
        }
    },
    'SAND':{
        'expe':{
            'no-opt':[],
            'opt':{
                'periodicity':1
            }
        }   
    },
    'Series2Graph':{
            'method':{
                'no-opt':['pattern_length'],
                'opt':{
                    'latent':None,
                    'rate':30,
                    'pruning':True
                }
            },
            'expe':{
                'no-opt':[],
                'opt':{
                    'periodicity':1
                }
            }
    },
    'SR':{
        'expe':{
            'no-opt':['window_size'],
            'opt':{
                'periodicity':1
            }
        } 
    }, 
    'Sub_PCA':{
        'expe':{
            'no-opt':[],
            'opt':{
                'periodicity':1, 
                'n_components':None,
                'n_jobs':1
            }
        }
    }, 
    'PCA':{
        'expe':{
            'no-opt':[],
            'opt':{
                'slidingWindow':100, 
                'n_components':None, 
                'n_jobs':1
            }
        }
    }, 
    'Sub_HBOS':{
        'expe':{
                'no-opt':[],
                'opt':{
                    'periodicity':1, 
                    'n_bins':10, 
                    'tol':0.5, 
                    'n_jobs':1
                }
        }
    }, 
    'HBOS':{
        'expe':{
                'no-opt':[],
                'opt':{
                    'slidingWindow':1,
                    'n_bins':10,
                    'tol':0.5,
                    'n_jobs':1
                }
        }
    }, 
    'Sub_OCSVM':{
        'expe':{
                'no-opt':[],
                'opt':{
                    'kernel':'rbf', 
                    'nu':0.5, 
                    'periodicity':1, 
                    'n_jobs':1
                }
        }
    }, 
    'OCSVM':{
        'expe':{
                'no-opt':[],
                'opt':{
                    'kernel':'rbf',
                    'nu':0.5, 
                    'slidingWindow':1,
                    'n_jobs':1
                }
        }
    }, 
    'Sub_MCD':{
        'expe':{
                'no-opt':[],
                'opt':{
                    'support_fraction':None, 
                    'periodicity':1, 
                    'n_jobs':1
                }
        }
    }, 
    'MCD':{
        'expe':{
                'no-opt':[],
                'opt':{
                    'support_fraction':None, 
                    'slidingWindow':1, 
                    'n_jobs':1
                }
        }
    }, 
    'Sub_KNN':{
        'expe':{
                'no-opt':[],
                'opt':{
                    'n_neighbors':10, 
                    'method':'largest', 
                    'periodicity':1, 
                    'n_jobs':1
                }
        }
    }, 
    'KNN':{
        'expe':{
                'no-opt':[],
                'opt':{
                    'slidingWindow':1, 
                    'n_neighbors':10, 
                    'method':'largest',
                    'n_jobs':1
                }
        }
    }, 
    'KMeansAD':{
        'expe':{
                'no-opt':[],
                'opt':{
                    'n_clusters':20, 
                    'window_size':20, 
                    'n_jobs':1
                }
        }
    }, 
    'KMeansAD_U':{
        'expe':{
                'no-opt':[],
                'opt':{
                    'n_clusters':20, 
                    'periodicity':1,
                    'n_jobs':1
                }
        }
    },
    'COPOD':{
        'expe':{
                'no-opt':[],
                'opt':{
                    'n_jobs':1
                }
        }
    }, 
    'CBLOF':{
        'expe':{
                'no-opt':[],
                'opt':{
                    'n_clusters':8, 
                    'alpha':0.9, 
                    'n_jobs':1
                }
        }
    }, 
    'COF':{
        'expe':{
                'no-opt':[],
                'opt':{
                    'n_neighbors':30
                }
        }
    }, 
    'EIF':{
        'expe':{
                'no-opt':[],
                'opt':{
                    'n_trees':100
                }
        }
    }, 
    'RobustPCA':{
        'expe':{
                'no-opt':[],
                'opt':{
                    'max_iter':1000
                }
        }
    }, 
    'SR':{
        'expe':{
                'no-opt':[],
                'opt':{
                    'periodicity':1
                }
        }
    }, 
    'AutoEncoder':{
        'expe':{
                'no-opt':[],
                'opt':{
                    'window_size':100,
                    'hidden_neurons':[64, 32], 
                    'n_jobs':1
                }
        }
    }, 
    'KShapeAD':{
        'method':{
            'no-opt':['k', 'window_size', 'stride'],
            'opt': {
                 'n_jobs':1, 
                'normalize':True
            }
        },
        'expe':{
                'no-opt':[],
                'opt':{
                    'periodicity':1
                }
        }
    },
    'FFT':{
        'method':{
            'no-opt':[],
            'opt':{
                'ifft_parameters':5, 
                'local_neighbor_window':21, 
                'local_outlier_threshold':0.6, 
                'max_region_size':50, 
                'max_sign_change_distance':10
            }
        },
        'expe':{
            'no-opt':[],
            'opt':{
                'ifft_parameters':5,
                'local_neighbor_window':21, 
                'local_outlier_threshold':0.6, 
                'max_region_size':50, 
                'max_sign_change_distance':10
                }
        }
    }, 
    'Left_STAMPi':{
        'method':{
                'no-opt':[],
                'opt':{
                    'n_init_train':100, 
                    'window_size':50, 
                    'normalize':True
                }
        },
        'expe':{
            'no-opt':[],
            'opt':{}
        }
    }, 
    'AutoEncoder':{
        'method':{
            'no-opt':[],
            'opt':{'slidingWindow':100,
                    'hidden_neurons':None,
                    'hidden_activation':'relu',
                    'batch_norm':True,
                    'learning_rate':1e-3,
                    'epochs':100,
                    'batch_size':32,
                    'dropout_rate':0.2,
                    'weight_decay':1e-5,
                    # validation_size=0.1,
                    'preprocessing':True,
                    'loss_fn':None,
                    'verbose':False,
                    # random_state=None,
                    'contamination':0.1,
                    'device':None
            }
        },
        'expe':{
            'no-opt':[],
            'opt':{
                'window_size':100,
                'hidden_neurons':[64, 32], 
                'n_jobs':1
            }
        }
    }, 
    'CNN':{ 
        'method':{
            'no-opt':['n_features'],
            'opt':{
                    'num_channel':[32, 32, 40],
                    'kernel_size':3,
                    'stride':1,
                    'predict_time_steps':1,
                    'dropout_rate':0.25,
                    'hidden_activation':'relu',
                    'device':'cpu'
            }
        },
        'expe':{
            'no-opt':[],
            'opt':{
               'window_size':100, 
               'num_channel':[32, 32, 40], 
               'lr':0.0008, 
               'n_jobs':1 
            }
        }
    },
    'LSTMAD':{
        'method':{
            'no-op':[],
            'opt': {
                'window_size':100,
                'pred_len':1,
                'batch_size':128,
                'epochs':50,
                'lr':0.0008,
                'feats':1,
                'hidden_dim':20,
                'num_layer':2,
                'validation_size':0.2
            }
        },
        'expe':{
            'no-opt':[],
            'opt':{
               'window_size':100,
                'lr':0.0008
            }
        }
    },
     'TranAD':{
         'method':{
            'no-opt': [],
            'opt':{
                'win_size':100,
                'feats':1,
                'batch_size':128,
                'epochs':50,
                'patience':3,
                'lr':1e-4,
                'validation_size':0.2
            }
         },
         'expe':{
             'no-opt': [],
            'opt':{
                'win_size':10,
                'lr':1e-3
            }
         }
     }, 
     'AnomalyTransformer':{
         'method':{
            'no-opt':[],
            'opt':{
                'win_size':100,
                'input_c':1,
                'num_epochs':10,
                'batch_size':128,
                'step':1,
                'k':3,
                'lr':1e-4,
                'patience':7,
                'validation_size':0.2
            }
         },
         'expe':{
            'no-opt':[],
            'opt':{
                'win_size':100,
                'lr':1e-4, 
                'batch_size':128
            }
         }
     }, 
     'OmniAnomaly':{
         'method':{
            'no-opt':[],
            'opt':{
                'win_size':5,
                'feats':1,
                'batch_size':128,
                'epochs':50,
                'patience':3,
                'lr':0.002,
                'validation_size':0.2
            }
         },
         'expe':{
            'no-opt':[],
            'opt':{
                'win_size':100,
                'lr':0.002
            }
         }
     }, 
     'USAD':{
         'method':{
            'no-opt':[],
            'opt':{
                'win_size':5,
                'feats':1,
                'batch_size':128,
                'epochs':10,
                'patience':3,
                'lr':1e-4,
                'validation_size':0.2
            }
         },
         'expe':{
            'no-opt':[],
            'opt':{
                'win_size':5, 
                'lr':1e-4
            } 
         }
     }, 
     'Donut':{
         'method':{
            'no-opt':[],
            'opt':{
                'win_size':120,
                'input_c':1,
                'batch_size':128,     # 32, 128
                'grad_clip':10.0,
                'num_epochs':50,
                'mc_samples':1024,
                'hidden_dim':100,
                'latent_dim':8,
                'inject_ratio':0.01,
                'lr':1e-4,
                'l2_coff':1e-3,
                'patience':3,
                'validation_size':0
            }
         },
         'expe':{
            'no-opt':[],
            'opt':{
                'win_size':120,
                'lr':1e-4, 
                'batch_size':128
            }
         }
     }, 
     'TimesNet':{
         'method':{
            'no-opt':[],
            'opt':{
                'win_size':96,
                'enc_in':1,
                'epochs':10,
                'batch_size':128,
                'lr':1e-4,
                'patience':3,
                'features':"M",
                'lradj':"type1",
                'validation_size':0.2
            }
         },
         'expe':{
            'no-opt':[],
            'opt':{
                'win_size':96, 
                'lr':1e-4
            }
         } 
     }, 
     'FITS':{
         'method':{
            'no-opt':[],
            'opt':{
                'win_size':100,
                'DSR':4,
                'individual':True,
                'input_c':1,
                'batch_size':128,
                'cut_freq':12,
                'epochs':50,
                'lr':1e-3,
                'validation_size':0.2
            }
         },
         'expe':{
            'no-opt':[],
            'opt':{
                'win_size':100,
                'lr':1e-3
            }
         }
     }, 
     'OFA':{
         'method':{
            'no-opt':[],
            'opt':{
                'win_size':100,
                'stride':1,
                'enc_in':1,
                'features':'M',
                'batch_size':128,
                'learning_rate':0.0001,
                'epochs':10,
                'patience':3,
                'lradj':"type1",
                'validation_size':0.2
            }
         },
         'expe':{
            'no-opt':[],
            'opt':{
                'win_size':100, 
                'batch_size':64
            }
         }
     }, 
     'Lag_Llama':{
         'method':{
            'no-opt':[],
            'opt':{
                'win_size':96, 
                'prediction_length':1, 
                'input_c':1,
                'use_rope_scaling':False,
                'batch_size':64,
                'num_samples':100,
                'ckpt_path':'lag-llama.ckpt'
            }
         },
         'expe':{
            'no-opt':[],
            'opt':{
                'win_size':96, 
                'batch_size':64
            }
         }
     }, 
     'Chronos':{
         'method':{
            'no-opt':[],
            'opt':{
                'win_size':100,
                'model_size':'base',  # [tiny, small, base]
                'prediction_length':1, 
                'input_c':1, 
                'batch_size':128
            }
         },
         'expe':{
            'no-opt':[],
            'opt':{
                'win_size':50, 
                'batch_size':64
            }
         }
     },
    'TimesFM':{
        'method':{
            'no-opt':[],
            'opt':{
                'win_size':96, 
                'prediction_length':1, 
                'input_c':1
            }
        },
        'expe':{
            'no-opt':[],
            'opt':{
                'win_size':96, 
            }
        }
    }, 
    'MOMENT_ZS':{
        'expe':{
            'no-opt':[],
            'opt':{
                'win_size':256, 
            }
        }
    }, 
    'MOMENT_FT':{
        'expe':{
            'no-opt':[],
            'opt':{
                'win_size':256, 
            }
        }
    },
    'M2N2':{
        'method':{
            'no-opt':[],
            'opt':{
                'win_size':12,
                'stride':12,
                'num_channels':1, 
                'batch_size':64,
                'epochs':10,
                'latent_dim':128,
                'lr':1e-3,
                'ttlr':1e-3, # learning rate for online test-time adaptation
                'normalization':"Detrend",
                'gamma':0.99,
                'th':0.95, # 95 percentile == 0.95 quantile
                'valid_size':0.2,
                'infer_mode':'online'
            }
        },
        'expe':{
            'no-opt':[],
            'opt':{
                'win_size':12, 
                'stride':12,
                'batch_size':64, 
                'epochs':100, 
                'latent_dim':16,
                'lr':1e-3, 
                'ttlr':1e-3, 
                'normalization':'Detrend',
                'gamma':0.99, 
                'th':0.9, 
                'valid_size':0.2, 
                'infer_mode':'online'
            }
        }
    }
}
