globals:
  comment: "Multitest"
  # user: pablo
  # hostname: generic

  db: 
#    file: /vol/FFL/code/pablo/results/results.db
    file: results/results-v5.db
    name: expe

  # paths:  # it is not mandatory to set those paths. if unset, values from defaults take places
  #   # by default, those dirs are relative to main script path
  #   temp_dir:     # ./temp
  #   result_dir:   # ./results
  #   log_dir:      # ./logs

runner:
  type: docker    # now, only docker is supported
  params:
    image: tsbad:0.0.4-cpu
    name: dazzling_bassi    # name or short_id of the container to be reused
    #command: 
    auto_remove: False
  limits:
  #   # cpus: 1
    mem_limit : [ 500m ]
    memswap_limit : [ 1g ]
  timeout: 6.5

##### For single test #####
# this section is added automatically. do not add it by hand!!!
# unit_test:
#   id: 000-000-000-000
#   result_file: results/000-000-000-000.yaml
#   # save_config: True

# dataset
dataset:
  # or function between: name, idx, group, re
  dir: /vol/FFL/datasets/TSB-AD-U
  summary: /vol/FFL/code/pablo/Summary.csv
  # name: 001_NAB_id_1_Facility_tr_1007_1st_2014
  index: [ 0 ]
  # group: [ WSD, NAB ]
  # re: "^123_|^035_"

# TSAD method
method: 
  name: [ LOF ]
    #  parameters: 
    #  slidingWindow: 1 
    #  n_neighbors: 30
    #  metric:  minkowski 
    #  n_jobs:  1

# metrics used for test. possible values: 'all', 'AUC-PR','AUC-ROC','VUS-PR','VUS-ROC','Standard-F1','PA-F1','Event-based-F1','R-based-F1','Affiliation-F'
metrics: all
  # PP: I drop metrics name and params, as it is not possible to pass params, so only keeping names straight under "metrics" key
  # name: all
  # parameters: ''



# ##### For multiple tests in one run #####
# test_serie:
#   methods:
#     - name: FFT
#     - name: HBOS
#   datasets:
#     summary: /vol/FFL/code/pablo/Summary.csv
#     filter:
#       idx: [ 0, 1, 2 ]
#       group: [ WSD, NAB ]
#       name: [ "149_Stock_id_1_Finance_tr_500_1st_7", "150_Stock_id_2_Finance_tr_500_1st_7" ]     
